name = "kauri-insight"
pages_build_output_dir = "apps/web/.vercel/output/static"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kauri-insight-db"
database_id = "356d244f-2ce4-485c-90ff-face2e079523"

[browser]
binding = "BROWSER"
