import { db } from '@kauri/db/client'
import { reports } from '@kauri/db/schema'
import { eq } from 'drizzle-orm'
import { notFound } from 'next/navigation'

export default async function ReportViewPage({ params }: { params: { id: string } }) {
    const report = await db.query.reports.findFirst({
        where: eq(reports.id, params.id),
        with: {
            sections: {
                orderBy: (sections, { asc }) => [asc(sections.orderIndex)],
            },
            survey: true,
        },
    })

    if (!report) {
        notFound()
    }

    return (
        <div className="max-w-[800px] mx-auto bg-white text-black p-0 sm:p-8 min-h-screen border shadow-sm print:shadow-none print:border-none">
            {/* Header */}
            <div className="border-b-4 border-primary pb-6 mb-8 flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-bold uppercase tracking-tight text-primary">Executive Report</h1>
                    <p className="text-xl text-muted-foreground mt-2">{report.title}</p>
                </div>
                <div className="text-right">
                    <p className="font-semibold text-primary">Kauri Insight</p>
                    <p className="text-sm text-muted-foreground">{new Date(report.createdAt).toLocaleDateString()}</p>
                </div>
            </div>

            {/* Executive Summary */}
            <div className="mb-10">
                <h2 className="text-2xl font-bold text-primary mb-4 border-b pb-2">1. Executive Summary</h2>
                <div className="text-lg leading-relaxed text-slate-800">
                    {report.summary}
                </div>
            </div>

            {/* Survey Details */}
            <div className="mb-10 p-4 bg-slate-50 border rounded-lg">
                <h3 className="text-sm font-semibold uppercase text-slate-500 mb-2">Survey Origin</h3>
                <p className="text-lg font-medium">{report.survey.name}</p>
                {report.survey.description && (
                    <p className="text-sm text-slate-600 mt-1">{report.survey.description}</p>
                )}
            </div>

            {/* Sections */}
            {report.sections.map((section, index) => (
                <div key={section.id} className="mb-12 break-inside-avoid">
                    <h2 className="text-2xl font-bold text-primary mb-4 border-b pb-2">
                        {index + 2}. {section.title}
                    </h2>
                    <div className="text-lg leading-relaxed text-slate-800 space-y-4">
                        {section.content.split('\n').map((para, i) => (
                            para ? <p key={i}>{para}</p> : <br key={i} />
                        ))}
                    </div>
                </div>
            ))}

            {/* Footer */}
            <div className="mt-20 pt-8 border-t text-center text-sm text-slate-400">
                <p>Generated by Kauri Insight AI Engine</p>
                <p>© {new Date().getFullYear()} Kauri Insight. All rights reserved.</p>
            </div>
        </div>
    )
}
