import PptxGenJS from 'pptxgenjs'
import type { Report } from '@kauri/shared/types'

export async function generatePPTX(report: Report): Promise<Buffer> {
  console.log('📊 Generating PowerPoint...')

  const prs = new PptxGenJS()

  // Set presentation properties
  prs.layout = 'LAYOUT_16x9'
  prs.author = 'Kauri Insight'
  prs.subject = report.title
  prs.title = report.title

  // Title slide
  const titleSlide = prs.addSlide()
  titleSlide.background = { color: '2563EB' }

  titleSlide.addText(report.title, {
    x: 1,
    y: 2.5,
    w: 8,
    h: 1,
    fontSize: 44,
    bold: true,
    color: 'FFFFFF',
    align: 'center',
  })

  titleSlide.addText('Generated by Kauri Insight', {
    x: 1,
    y: 4,
    w: 8,
    h: 0.5,
    fontSize: 18,
    color: 'E0E0E0',
    align: 'center',
  })

  // Executive summary slide
  if (report.executiveSummary) {
    const summarySlide = prs.addSlide()
    summarySlide.addText('Executive Summary', {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.6,
      fontSize: 32,
      bold: true,
      color: '1E293B',
    })

    summarySlide.addText(report.executiveSummary, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 3.5,
      fontSize: 16,
      color: '475569',
      valign: 'top',
    })
  }

  // Section slides
  for (const section of report.sections) {
    const slide = prs.addSlide()

    slide.addText(section.heading, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.6,
      fontSize: 28,
      bold: true,
      color: '1E293B',
    })

    slide.addText(section.body, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 3.5,
      fontSize: 14,
      color: '475569',
      valign: 'top',
    })

    // Add metrics if available
    if (section.metrics && Object.keys(section.metrics).length > 0) {
      const metricsY = 5.2
      let metricsX = 0.5

      for (const [key, value] of Object.entries(section.metrics)) {
        slide.addText(`${key}: ${value}`, {
          x: metricsX,
          y: metricsY,
          w: 2.5,
          h: 0.4,
          fontSize: 12,
          color: '64748B',
        })
        metricsX += 3
      }
    }
  }

  console.log('✅ PowerPoint generated successfully')

  // Return as buffer
  const buffer = (await prs.write({ outputType: 'arraybuffer' })) as ArrayBuffer
  return Buffer.from(buffer)
}
